# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='database.proto',
  package='compendium',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x64\x61tabase.proto\x12\ncompendium\"\x06\n\x04Void\"&\n\x05\x41rray\x12\x1d\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0f.compendium.Any\"r\n\x06Object\x12*\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1c.compendium.Object.DataEntry\x1a<\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.compendium.Any:\x02\x38\x01\"\x11\n\x03Ref\x12\n\n\x02to\x18\x01 \x01(\t\"\x14\n\x04\x46ile\x12\x0c\n\x04path\x18\x01 \x01(\t\"@\n\x04\x45xec\x12\x0e\n\x04\x63ode\x18\x01 \x01(\tH\x00\x12 \n\x04\x66ile\x18\x02 \x01(\x0b\x32\x10.compendium.FileH\x00\x42\x06\n\x04todo\"\xe0\x02\n\x03\x41ny\x12 \n\x04null\x18\x01 \x01(\x0b\x32\x10.compendium.VoidH\x00\x12 \n\x04\x62ool\x18\x02 \x01(\x0e\x32\x10.compendium.BoolH\x00\x12\r\n\x03int\x18\x03 \x01(\x03H\x00\x12\x0f\n\x05\x66loat\x18\x04 \x01(\x01H\x00\x12\r\n\x03str\x18\x05 \x01(\tH\x00\x12\x0e\n\x04\x62lob\x18\x06 \x01(\x0cH\x00\x12\"\n\x05\x61rray\x18\x07 \x01(\x0b\x32\x11.compendium.ArrayH\x00\x12 \n\x03set\x18\x08 \x01(\x0b\x32\x11.compendium.ArrayH\x00\x12$\n\x06object\x18\t \x01(\x0b\x32\x12.compendium.ObjectH\x00\x12\x1e\n\x03ref\x18\n \x01(\x0b\x32\x0f.compendium.RefH\x00\x12 \n\x04\x66ile\x18\x0b \x01(\x0b\x32\x10.compendium.FileH\x00\x12 \n\x04\x65xec\x18\x0c \x01(\x0b\x32\x10.compendium.ExecH\x00\x42\x06\n\x04\x64\x61ta\"\x82\x01\n\x08\x44\x61tabase\x12\x32\n\x07\x65ntries\x18\x01 \x03(\x0b\x32!.compendium.Database.EntriesEntry\x1a\x42\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.compendium.Object:\x02\x38\x01*\x1b\n\x04\x42ool\x12\t\n\x05\x66\x61lse\x10\x00\x12\x08\n\x04true\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_BOOL = _descriptor.EnumDescriptor(
  name='Bool',
  full_name='compendium.Bool',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='false', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='true', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=789,
  serialized_end=816,
)
_sym_db.RegisterEnumDescriptor(_BOOL)

Bool = enum_type_wrapper.EnumTypeWrapper(_BOOL)
false = 0
true = 1



_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='compendium.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=36,
)


_ARRAY = _descriptor.Descriptor(
  name='Array',
  full_name='compendium.Array',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='compendium.Array.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=76,
)


_OBJECT_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='compendium.Object.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='compendium.Object.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='compendium.Object.DataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=192,
)

_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='compendium.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='compendium.Object.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_OBJECT_DATAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=192,
)


_REF = _descriptor.Descriptor(
  name='Ref',
  full_name='compendium.Ref',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='to', full_name='compendium.Ref.to', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=211,
)


_FILE = _descriptor.Descriptor(
  name='File',
  full_name='compendium.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='compendium.File.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=233,
)


_EXEC = _descriptor.Descriptor(
  name='Exec',
  full_name='compendium.Exec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='compendium.Exec.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file', full_name='compendium.Exec.file', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='todo', full_name='compendium.Exec.todo',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=235,
  serialized_end=299,
)


_ANY = _descriptor.Descriptor(
  name='Any',
  full_name='compendium.Any',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='null', full_name='compendium.Any.null', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool', full_name='compendium.Any.bool', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int', full_name='compendium.Any.int', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float', full_name='compendium.Any.float', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='str', full_name='compendium.Any.str', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blob', full_name='compendium.Any.blob', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='array', full_name='compendium.Any.array', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='set', full_name='compendium.Any.set', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object', full_name='compendium.Any.object', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ref', full_name='compendium.Any.ref', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file', full_name='compendium.Any.file', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exec', full_name='compendium.Any.exec', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='compendium.Any.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=302,
  serialized_end=654,
)


_DATABASE_ENTRIESENTRY = _descriptor.Descriptor(
  name='EntriesEntry',
  full_name='compendium.Database.EntriesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='compendium.Database.EntriesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='compendium.Database.EntriesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=721,
  serialized_end=787,
)

_DATABASE = _descriptor.Descriptor(
  name='Database',
  full_name='compendium.Database',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='compendium.Database.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATABASE_ENTRIESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=657,
  serialized_end=787,
)

_ARRAY.fields_by_name['data'].message_type = _ANY
_OBJECT_DATAENTRY.fields_by_name['value'].message_type = _ANY
_OBJECT_DATAENTRY.containing_type = _OBJECT
_OBJECT.fields_by_name['data'].message_type = _OBJECT_DATAENTRY
_EXEC.fields_by_name['file'].message_type = _FILE
_EXEC.oneofs_by_name['todo'].fields.append(
  _EXEC.fields_by_name['code'])
_EXEC.fields_by_name['code'].containing_oneof = _EXEC.oneofs_by_name['todo']
_EXEC.oneofs_by_name['todo'].fields.append(
  _EXEC.fields_by_name['file'])
_EXEC.fields_by_name['file'].containing_oneof = _EXEC.oneofs_by_name['todo']
_ANY.fields_by_name['null'].message_type = _VOID
_ANY.fields_by_name['bool'].enum_type = _BOOL
_ANY.fields_by_name['array'].message_type = _ARRAY
_ANY.fields_by_name['set'].message_type = _ARRAY
_ANY.fields_by_name['object'].message_type = _OBJECT
_ANY.fields_by_name['ref'].message_type = _REF
_ANY.fields_by_name['file'].message_type = _FILE
_ANY.fields_by_name['exec'].message_type = _EXEC
_ANY.oneofs_by_name['data'].fields.append(
  _ANY.fields_by_name['null'])
_ANY.fields_by_name['null'].containing_oneof = _ANY.oneofs_by_name['data']
_ANY.oneofs_by_name['data'].fields.append(
  _ANY.fields_by_name['bool'])
_ANY.fields_by_name['bool'].containing_oneof = _ANY.oneofs_by_name['data']
_ANY.oneofs_by_name['data'].fields.append(
  _ANY.fields_by_name['int'])
_ANY.fields_by_name['int'].containing_oneof = _ANY.oneofs_by_name['data']
_ANY.oneofs_by_name['data'].fields.append(
  _ANY.fields_by_name['float'])
_ANY.fields_by_name['float'].containing_oneof = _ANY.oneofs_by_name['data']
_ANY.oneofs_by_name['data'].fields.append(
  _ANY.fields_by_name['str'])
_ANY.fields_by_name['str'].containing_oneof = _ANY.oneofs_by_name['data']
_ANY.oneofs_by_name['data'].fields.append(
  _ANY.fields_by_name['blob'])
_ANY.fields_by_name['blob'].containing_oneof = _ANY.oneofs_by_name['data']
_ANY.oneofs_by_name['data'].fields.append(
  _ANY.fields_by_name['array'])
_ANY.fields_by_name['array'].containing_oneof = _ANY.oneofs_by_name['data']
_ANY.oneofs_by_name['data'].fields.append(
  _ANY.fields_by_name['set'])
_ANY.fields_by_name['set'].containing_oneof = _ANY.oneofs_by_name['data']
_ANY.oneofs_by_name['data'].fields.append(
  _ANY.fields_by_name['object'])
_ANY.fields_by_name['object'].containing_oneof = _ANY.oneofs_by_name['data']
_ANY.oneofs_by_name['data'].fields.append(
  _ANY.fields_by_name['ref'])
_ANY.fields_by_name['ref'].containing_oneof = _ANY.oneofs_by_name['data']
_ANY.oneofs_by_name['data'].fields.append(
  _ANY.fields_by_name['file'])
_ANY.fields_by_name['file'].containing_oneof = _ANY.oneofs_by_name['data']
_ANY.oneofs_by_name['data'].fields.append(
  _ANY.fields_by_name['exec'])
_ANY.fields_by_name['exec'].containing_oneof = _ANY.oneofs_by_name['data']
_DATABASE_ENTRIESENTRY.fields_by_name['value'].message_type = _OBJECT
_DATABASE_ENTRIESENTRY.containing_type = _DATABASE
_DATABASE.fields_by_name['entries'].message_type = _DATABASE_ENTRIESENTRY
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['Array'] = _ARRAY
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
DESCRIPTOR.message_types_by_name['Ref'] = _REF
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['Exec'] = _EXEC
DESCRIPTOR.message_types_by_name['Any'] = _ANY
DESCRIPTOR.message_types_by_name['Database'] = _DATABASE
DESCRIPTOR.enum_types_by_name['Bool'] = _BOOL

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'database_pb2'
  # @@protoc_insertion_point(class_scope:compendium.Void)
  ))
_sym_db.RegisterMessage(Void)

Array = _reflection.GeneratedProtocolMessageType('Array', (_message.Message,), dict(
  DESCRIPTOR = _ARRAY,
  __module__ = 'database_pb2'
  # @@protoc_insertion_point(class_scope:compendium.Array)
  ))
_sym_db.RegisterMessage(Array)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), dict(

  DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), dict(
    DESCRIPTOR = _OBJECT_DATAENTRY,
    __module__ = 'database_pb2'
    # @@protoc_insertion_point(class_scope:compendium.Object.DataEntry)
    ))
  ,
  DESCRIPTOR = _OBJECT,
  __module__ = 'database_pb2'
  # @@protoc_insertion_point(class_scope:compendium.Object)
  ))
_sym_db.RegisterMessage(Object)
_sym_db.RegisterMessage(Object.DataEntry)

Ref = _reflection.GeneratedProtocolMessageType('Ref', (_message.Message,), dict(
  DESCRIPTOR = _REF,
  __module__ = 'database_pb2'
  # @@protoc_insertion_point(class_scope:compendium.Ref)
  ))
_sym_db.RegisterMessage(Ref)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), dict(
  DESCRIPTOR = _FILE,
  __module__ = 'database_pb2'
  # @@protoc_insertion_point(class_scope:compendium.File)
  ))
_sym_db.RegisterMessage(File)

Exec = _reflection.GeneratedProtocolMessageType('Exec', (_message.Message,), dict(
  DESCRIPTOR = _EXEC,
  __module__ = 'database_pb2'
  # @@protoc_insertion_point(class_scope:compendium.Exec)
  ))
_sym_db.RegisterMessage(Exec)

Any = _reflection.GeneratedProtocolMessageType('Any', (_message.Message,), dict(
  DESCRIPTOR = _ANY,
  __module__ = 'database_pb2'
  # @@protoc_insertion_point(class_scope:compendium.Any)
  ))
_sym_db.RegisterMessage(Any)

Database = _reflection.GeneratedProtocolMessageType('Database', (_message.Message,), dict(

  EntriesEntry = _reflection.GeneratedProtocolMessageType('EntriesEntry', (_message.Message,), dict(
    DESCRIPTOR = _DATABASE_ENTRIESENTRY,
    __module__ = 'database_pb2'
    # @@protoc_insertion_point(class_scope:compendium.Database.EntriesEntry)
    ))
  ,
  DESCRIPTOR = _DATABASE,
  __module__ = 'database_pb2'
  # @@protoc_insertion_point(class_scope:compendium.Database)
  ))
_sym_db.RegisterMessage(Database)
_sym_db.RegisterMessage(Database.EntriesEntry)


_OBJECT_DATAENTRY.has_options = True
_OBJECT_DATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_DATABASE_ENTRIESENTRY.has_options = True
_DATABASE_ENTRIESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
